# Generated by Django 5.2 on 2025-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_banner_image_banner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='', upload_to='networks')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
            },
        ),
    ]
