# Generated by Django 5.2 on 2025-04-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Категория достижения',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость'},
        ),
        migrations.CreateModel(
            name='AchievCategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_in', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='', upload_to='achievements/')),
                ('author', models.TextField(max_length=255)),
                ('project_file', models.FileField(upload_to='project_file/')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='website.achievcategory')),
            ],
        ),
    ]
